name: .NET Core

on:
  pull_request:
    branches: 
      master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: testing secrets
      run: |
        export x="this is for testing secrets"
        echo "the variable x is -> $x"
        echo "the variable x is -> ${{ env.x }} "
        
