name: .NET Core

on:
  pull_request:
    branches: 
      master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: testing secrets
      run: |
        echo "x=this is secret" >> $GITHUB_ENV
        echo "the variable x is -> $x"
        echo "the variable x is -> ${{ env.x }} "
    - name: testing secrets2
      run: |
        echo "the variable x is -> ${{ env.x }} "
